options:
  flip_visual_attachments: True
  fix_base_link: True  
  disable_gravity: True
  collapse_fixed_joints: False
  enable_gyroscopic_forces: True

  thickness: 0.0
  density: 1000.0
  armature: 0.01
  friction: 0.1
  stiffness: 0.0
  damping: 0.0

  use_physx_armature: True
  convex_decomposition_from_submeshes: True  
  use_mesh_materials: True
  disable_self_collision: True

stable_damping:
  linear_damping: 1.0
  max_linear_velocity: 1.0
  angular_damping: 5.0
  max_angular_velocity: 6.283184  
default_damping:
  linear_damping: 0.0
  max_linear_velocity: 1.0
  angular_damping: 0.5
  max_angular_velocity: 6.283184  

properties:
  friction:
    default: 1.0
    rolling: 0.0
    torsion: 0.0
  restitution: 0.0
  compliance: 0.0
  contact_offset: 0.002
  rest_offset: 0.0

sensor:
  bodies: ['ft_sensor_link']
  enable_forward_dynamics_forces: False
  enable_constraint_solver_forces: True
  use_world_frame: False
